### ISSUE TITLE
ISO19139 is not separate from ISO19115

### ISSUE THREAD

**Issue by sjskhalsa** [rd-alliance/metadata-catalog-dev#30]
I notice in the list of schema that 19139 is listed separately from 19115.  19139 is the spec for xml implementation of the 19115 abstract model.

**Comment by alex-ball** [comment]
The stub for 19139 was generated in the migration from the Metadata Standards Directory as an endpoint for one of the mappings. I will look at merging it into the one for 19115.

**Comment by dr-shorthair** [comment]
However, the revision ISO 19139-1 is decoupled from the metadata standards. The metadata-specific aspects have been moved over into ISO 19115-3. ISO 19139-1 is just the UML->XML conversion rule that could be applied to all the ISO 191NN series models. Depending on the scope of this catalog, you might want to drop ISO 19139-1 altogether (its not about metadata) else keep it separate (its not about 19115 any more).

**Comment by alex-ball** [comment]
The scope of the catalogue is defined in terms of specifications for metadata elements, attributes and relationships, rather than file formats and serializations. I think it makes most sense to explain about ISO 19139-3 in the entry for ISO 19115.

**Comment by dr-shorthair** [comment]
In that case I suggest dropping 19139 from the catalogue - for your purposes it is fully superseded by ISO 19115-3 - https://www.iso.org/standard/32579.html

**Comment by alex-ball** [comment]
For avoidance of any further doubt, when I say 'merge into the one for ISO 19115', that means having an entry for ISO 19115 and not having one for ISO 19139, and the crosswalk that currently says it transforms to ISO 19139 will be listed as transforming to ISO 19115.

**Comment by alex-ball** [comment]
This should now be fixed.
