### ISSUE TITLE
Some catalog functions not available

### ISSUE THREAD

**Issue by dr-shorthair** [rd-alliance/metadata-catalog-dev#31]
I'm trying to update http://rdamsc.dcc.ac.uk/msc/m12 but getting 'Page unavailable'.

**Comment by dr-shorthair** [comment]
Search is up and down as well http://rdamsc.dcc.ac.uk/search

**Comment by alex-ball** [comment]
I am aware that we are having some teething troubles with the Catalog, and that it is not behaving as written. I do not have access to the server personally, but I will suggest to my sysadmin team (!) that we do a fresh re-install next week.

**Comment by alex-ball** [comment]
The issue you experienced has now been fixed. Please open a new issue if you experience any further odd behaviour.

In the course of diagnosing the problem we had to roll back some changes, so you may need to reapply them. Apologies for the inconvenience.
